const heading = document.querySelector('#Jheader')
const message = document.querySelector('#Jtexts')
let y = document.getElementById("j1")
let x = document.getElementById("j2")

function jitem1(){
    document.getElementById("item1").className = "Jactive1"
    document.getElementById("item2").className = "cont2"
    document.getElementById("item3").className = "cont2"
    document.getElementById("item4").className = "cont2"
    document.getElementById("item5").className = "cont2"
    document.getElementById("img1").src = "active.png"
    document.getElementById("img2").src = "inactive.png"
    document.getElementById("img3").src = "inactive.png"
    document.getElementById("img4").src = "inactive.png"
    document.getElementById("img5").src = "inactive.png"
    document.getElementById("item6").className = "Jactive2"
    document.getElementById("item7").className = "cont3"
    document.getElementById("item8").className = "cont3"
    document.getElementById("item9").className = "cont3"
    document.getElementById("item10").className = "cont3"
    document.getElementById("image1").src = "Jimg.png"
    heading.innerHTML = "Efficient Policy Manangement"
    message.innerHTML = "Your customers have full control over policies purchased from you. The app is made to take the worry off you in managing all insurance activities."
    // y.style.marginLeft = "5%"
    // y.style.transition = "1s"
}
function jitem2(){
    document.getElementById("item1").className = "cont2"
    document.getElementById("item2").className = "Jactive1"
    document.getElementById("item3").className = "cont2"
    document.getElementById("item4").className = "cont2"
    document.getElementById("item5").className = "cont2"
    document.getElementById("img1").src = "inactive.png"
    document.getElementById("img2").src = "active.png"
    document.getElementById("img3").src = "inactive.png"
    document.getElementById("img4").src = "inactive.png"
    document.getElementById("img5").src = "inactive.png"
    document.getElementById("item6").className = "cont3"
    document.getElementById("item7").className = "Jactive2"
    document.getElementById("item8").className = "cont3"
    document.getElementById("item9").className = "cont3"
    document.getElementById("item10").className = "cont3"
    document.getElementById("image1").src = "Jimg2.png"
    heading.innerHTML = "Simple Wallet System"
    message.innerHTML = "A wallet system for your customers to renew policies and receive claim payouts instantly."
    // x.style.marginLeft = "5%"
    // x.style.transition = "1s"
}
function jitem3(){
    document.getElementById("item1").className = "cont2"
    document.getElementById("item2").className = "cont2"
    document.getElementById("item3").className = "Jactive1"
    document.getElementById("item4").className = "cont2"
    document.getElementById("item5").className = "cont2"
    document.getElementById("img1").src = "inactive.png"
    document.getElementById("img2").src = "inactive.png"
    document.getElementById("img3").src = "active.png"
    document.getElementById("img4").src = "inactive.png"
    document.getElementById("img5").src = "inactive.png"
    document.getElementById("item6").className = "cont3"
    document.getElementById("item7").className = "cont3"
    document.getElementById("item8").className = "Jactive2"
    document.getElementById("item9").className = "cont3"
    document.getElementById("item10").className = "cont3"
    document.getElementById("image1").src = "Jimg3.png"
    heading.innerHTML = "Intuitive Claims Management"
    message.innerHTML = "Customers enjoy fast claims assessment by lodging claims, track status, and swift payouts from anywhere"
    // let x = document.getElementById("j3")
    // x.style.marginLeft = "5%"
    // x.style.transition = "1s"
}
function jitem4(){
    document.getElementById("item1").className = "cont2"
    document.getElementById("item2").className = "cont2"
    document.getElementById("item3").className = "cont2"
    document.getElementById("item4").className = "Jactive1"
    document.getElementById("item5").className = "cont2"
    document.getElementById("img1").src = "inactive.png"
    document.getElementById("img2").src = "inactive.png"
    document.getElementById("img3").src = "inactive.png"
    document.getElementById("img4").src = "active.png"
    document.getElementById("img5").src = "inactive.png"
    document.getElementById("item6").className = "cont3"
    document.getElementById("item7").className = "cont3"
    document.getElementById("item8").className = "cont3"
    document.getElementById("item9").className = "Jactive2"
    document.getElementById("item10").className = "cont3"
    document.getElementById("image1").src = "Jimg4.png"
    heading.innerHTML = "E-HMO ID"
    message.innerHTML = "Your customers can manage and use their health insurance plans via a digital HMO ID from anywhere."
    // let x = document.getElementById("j4")
    // x.style.marginLeft = "5%"
    // x.style.transition = "1s"
}
function jitem5(){
    document.getElementById("item1").className = "cont2"
    document.getElementById("item2").className = "cont2"
    document.getElementById("item3").className = "cont2"
    document.getElementById("item4").className = "cont2"
    document.getElementById("item5").className = "Jactive1"
    document.getElementById("img1").src = "inactive.png"
    document.getElementById("img2").src = "inactive.png"
    document.getElementById("img3").src = "inactive.png"
    document.getElementById("img4").src = "inactive.png"
    document.getElementById("img5").src = "active.png"
    document.getElementById("item6").className = "cont3"
    document.getElementById("item7").className = "cont3"
    document.getElementById("item8").className = "cont3"
    document.getElementById("item9").className = "cont3"
    document.getElementById("item10").className = "Jactive2"
    document.getElementById("image1").src = "Jimg5.png"
    heading.innerHTML = "Fraud-free Inspection"
    message.innerHTML = "The perfect solution for efficient inspection and real-time assessments without any human influence."
    // let x = document.getElementById("j5")
    // x.style.marginLeft = "5%"
    // x.style.transition = "1s"
}

// const element = document.getElementById("demo");
// setInterval(function() {element.innerHTML += "Hello"}, 1000);
